version = 1

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.13.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"
